package com.yiba.vo;

public class AgenKpiInfoVO {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column agen_kpi_info.id
     *
     * @mbggenerated Thu Sep 10 14:04:53 CST 2015
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column agen_kpi_info.kpi_sn
     *
     * @mbggenerated Thu Sep 10 14:04:53 CST 2015
     */
    private String kpiSn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column agen_kpi_info.dept_id
     *
     * @mbggenerated Thu Sep 10 14:04:53 CST 2015
     */
    private Long deptId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column agen_kpi_info.type
     *
     * @mbggenerated Thu Sep 10 14:04:53 CST 2015
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column agen_kpi_info.name
     *
     * @mbggenerated Thu Sep 10 14:04:53 CST 2015
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column agen_kpi_info.parent_id
     *
     * @mbggenerated Thu Sep 10 14:04:53 CST 2015
     */
    private Long parentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column agen_kpi_info.create_id
     *
     * @mbggenerated Thu Sep 10 14:04:53 CST 2015
     */
    private Long createId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column agen_kpi_info.create_time
     *
     * @mbggenerated Thu Sep 10 14:04:53 CST 2015
     */
    private Long createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column agen_kpi_info.id
     *
     * @return the value of agen_kpi_info.id
     *
     * @mbggenerated Thu Sep 10 14:04:53 CST 2015
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column agen_kpi_info.id
     *
     * @param id the value for agen_kpi_info.id
     *
     * @mbggenerated Thu Sep 10 14:04:53 CST 2015
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column agen_kpi_info.kpi_sn
     *
     * @return the value of agen_kpi_info.kpi_sn
     *
     * @mbggenerated Thu Sep 10 14:04:53 CST 2015
     */
    public String getKpiSn() {
        return kpiSn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column agen_kpi_info.kpi_sn
     *
     * @param kpiSn the value for agen_kpi_info.kpi_sn
     *
     * @mbggenerated Thu Sep 10 14:04:53 CST 2015
     */
    public void setKpiSn(String kpiSn) {
        this.kpiSn = kpiSn == null ? null : kpiSn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column agen_kpi_info.dept_id
     *
     * @return the value of agen_kpi_info.dept_id
     *
     * @mbggenerated Thu Sep 10 14:04:53 CST 2015
     */
    public Long getDeptId() {
        return deptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column agen_kpi_info.dept_id
     *
     * @param deptId the value for agen_kpi_info.dept_id
     *
     * @mbggenerated Thu Sep 10 14:04:53 CST 2015
     */
    public void setDeptId(Long deptId) {
        this.deptId = deptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column agen_kpi_info.type
     *
     * @return the value of agen_kpi_info.type
     *
     * @mbggenerated Thu Sep 10 14:04:53 CST 2015
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column agen_kpi_info.type
     *
     * @param type the value for agen_kpi_info.type
     *
     * @mbggenerated Thu Sep 10 14:04:53 CST 2015
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column agen_kpi_info.name
     *
     * @return the value of agen_kpi_info.name
     *
     * @mbggenerated Thu Sep 10 14:04:53 CST 2015
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column agen_kpi_info.name
     *
     * @param name the value for agen_kpi_info.name
     *
     * @mbggenerated Thu Sep 10 14:04:53 CST 2015
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column agen_kpi_info.parent_id
     *
     * @return the value of agen_kpi_info.parent_id
     *
     * @mbggenerated Thu Sep 10 14:04:53 CST 2015
     */
    public Long getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column agen_kpi_info.parent_id
     *
     * @param parentId the value for agen_kpi_info.parent_id
     *
     * @mbggenerated Thu Sep 10 14:04:53 CST 2015
     */
    public void setParentId(Long parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column agen_kpi_info.create_id
     *
     * @return the value of agen_kpi_info.create_id
     *
     * @mbggenerated Thu Sep 10 14:04:53 CST 2015
     */
    public Long getCreateId() {
        return createId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column agen_kpi_info.create_id
     *
     * @param createId the value for agen_kpi_info.create_id
     *
     * @mbggenerated Thu Sep 10 14:04:53 CST 2015
     */
    public void setCreateId(Long createId) {
        this.createId = createId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column agen_kpi_info.create_time
     *
     * @return the value of agen_kpi_info.create_time
     *
     * @mbggenerated Thu Sep 10 14:04:53 CST 2015
     */
    public Long getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column agen_kpi_info.create_time
     *
     * @param createTime the value for agen_kpi_info.create_time
     *
     * @mbggenerated Thu Sep 10 14:04:53 CST 2015
     */
    public void setCreateTime(Long createTime) {
        this.createTime = createTime;
    }
}