package com.yiba.dto;

import com.yiba.vo.AgenKpiInfoVO;

public interface AgenKpiInfoVOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table agen_kpi_info
     *
     * @mbggenerated Thu Sep 10 14:04:53 CST 2015
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table agen_kpi_info
     *
     * @mbggenerated Thu Sep 10 14:04:53 CST 2015
     */
    int insert(AgenKpiInfoVO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table agen_kpi_info
     *
     * @mbggenerated Thu Sep 10 14:04:53 CST 2015
     */
    int insertSelective(AgenKpiInfoVO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table agen_kpi_info
     *
     * @mbggenerated Thu Sep 10 14:04:53 CST 2015
     */
    AgenKpiInfoVO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table agen_kpi_info
     *
     * @mbggenerated Thu Sep 10 14:04:53 CST 2015
     */
    int updateByPrimaryKeySelective(AgenKpiInfoVO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table agen_kpi_info
     *
     * @mbggenerated Thu Sep 10 14:04:53 CST 2015
     */
    int updateByPrimaryKey(AgenKpiInfoVO record);
}